spring:
  application:
    name: Shortener

short-code:
  max-length: 8
  max-store-size: 2000
  gc-rate: 0.2
  short-url-host: https://shortener.com
  lock-config:
    timeout: 10
    timeunit: SECONDS
    max-pool-size: 100